## 1. ndarray
### 1) 다차원 배열 클래스



In [4]:
import numpy as np

In [14]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([[1,2,3],[2,3,4]])
c = np.array(["hello", "python", "ora"])

print(a)
print(type(a))
print(b)
peinr(c)


print("shape : ", a.shape)
print("shape : ", b.shape)
print("shape : ", c.shape)

print("ndim : ", a.ndim)
print("ndim : ", b.ndim)
print("ndim : ", c.ndim)

print("dtype : ", a.dtype)
print("dtype : ", b.dtype)
print("dtype : ", c.dtype)

print("itemsize : ", a.itemsize)
print("itemsize : ", b.itemsize)
print("itemsize : ", c.itemsize)
      

print("size : ", a.size)
print("size : ", b.size)
print("size : ", c.size)


[1 2 3 4 5]
<class 'numpy.ndarray'>
shape :  (5,)
shape :  (2, 3)
shape :  (3,)
ndim :  1
ndim :  2
ndim :  1
dtype :  int32
dtype :  int32
dtype :  <U6
itemsize :  4
itemsize :  4
itemsize :  24
size :  5
size :  6
size :  3


### 2) 주요 메서드 / 함수

In [16]:
# max, min, mean
a = np.array([1, 2, 3, 4, 5])
print(a.max(), a.min(), a.mean())

5 1 3.0


In [17]:
# flatten
b = np.array([ [1,2],[3,4],[5,6]])
print(b)
print(b.flatten())

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [24]:
# np.append
a = np.array([1,2,3])
b = np.array([ [4,5,6],[7,8,9] ])
print(np.append(a,b))
print(np.append([a],b,axis=0))
c = np.array([ [11, 12, 13], [13, 14, 15]  ])
print(np.append(b,c,axis=0))
print(np.append(b,c,axis=1))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [13 14 15]]
[[ 4  5  6 11 12 13]
 [ 7  8  9 13 14 15]]


### 3) ndarray 생성 함수

In [31]:
print(np.zeros((3,3)))
print(np.ones((3,2)))
print(np.full((3,2),10))
print(np.eye(4))
print(np.arange(1,10,2))


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[10 10]
 [10 10]
 [10 10]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[0 2 4 6 8]


In [39]:
# ndarray 재구성
a = np.arange(1,20,2)
print(a)
print(a.reshape(5,2))

b = np.arange(1,20,2).reshape(5,2)
print(b)
print(np.transpose(b))


[ 1  3  5  7  9 11 13 15 17 19]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]
[[ 1  5  9 13 17]
 [ 3  7 11 15 19]]


### 4) 다차원 배열의 축

In [40]:
# sum()
a = np.arange(1,7).reshape(3,2)
print(a)

print(a.sum(axis=0))
print(a.sum(axis=1))


[[1 2]
 [3 4]
 [5 6]]
[ 9 12]
[ 3  7 11]


In [45]:
# insert, delete
a = np.arange(1,7).reshape(3,2)
print(np.insert(a, 1, 10, axis=0))
print(np.insert(a, 1, 20, axis=1))
print("--------------------------------------")
b = np.insert(a, 1, 10, axis=0)
print(b)
np.insert(b, 1, 30, axis=1)
print("--------------------------------------")
print(b)
print(np.delete(b, 1, axis=0))
print(np.delete(b, 1, axis=1))

[[ 1  2]
 [10 10]
 [ 3  4]
 [ 5  6]]
[[ 1 20  2]
 [ 3 20  4]
 [ 5 20  6]]
--------------------------------------
[[ 1  2]
 [10 10]
 [ 3  4]
 [ 5  6]]
--------------------------------------
[[ 1  2]
 [10 10]
 [ 3  4]
 [ 5  6]]
[[1 2]
 [3 4]
 [5 6]]
[[ 1]
 [10]
 [ 3]
 [ 5]]


### 5) 인덱싱과 슬라이싱

In [47]:
# 1차원 배열 인덱싱 :list와 동일
a = np.arange(5)
print(a)
print(a[0], a[3], a[-1])

[0 1 2 3 4]
0 3 4


In [52]:
# 1차원 배열의 인덱싱 (여러 개 원소 인덱싱)
a = np.arange(5)
print(a)
print(a[0], a[3], a[-1])


[0 1 2 3 4]
0 3 4


In [53]:
# 1차원 배열의 인덱싱 (여러 개 원소 인덱싱)
a = np.arange(5)

print(a[[0, 3, -1]])

[0 3 4]


In [54]:
#1차원 배열의 슬라이싱 : list와 동일
a = np.arange(10)
print(a)
print(a[:3])
print(a[3:7])
print(a[::2])
print(a[::-1])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[3 4 5 6]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [58]:
# 2차원 배열의 인덱싱
a = np.array([ [1,2], [3,4], [5,6] ])
print(a)
print(a[0][1])
print(a[2][1])

print(a[0,1])
print(a[2,1])


[[1 2]
 [3 4]
 [5 6]]
2
6
2
6


In [59]:
# 2차원 배열의 슬라이싱
a = np.array([ [1,2], [3,4], [5,6]])

print(a[:2])
print(a[:2][1])
print(a[:2][1][1])

print(a[:2, 1])

[[1 2]
 [3 4]]
[3 4]
4
[2 4]
